name: Keep Render Service Alive

on:
  schedule:
    # Ping every 14 minutes (free tier sleeps after 15 minutes of inactivity)
    - cron: '*/14 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  ping-service:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping MediaFlow Proxy
        run: |
          echo "Pinging MediaFlow Proxy to keep it alive..."
          
          # Replace with your actual Render URL
          RENDER_URL="https://mediaflow-proxy-0fzf.onrender.com"
          API_PASSWORD="${{ secrets.API_PASSWORD }}"
          
          # Ping the health endpoint
          response=$(curl -s -o /dev/null -w "%{http_code}" "$RENDER_URL/" || echo "000")
          
          if [ "$response" = "200" ] || [ "$response" = "403" ]; then
            echo "✅ Service is alive! HTTP Status: $response"
          else
            echo "⚠️ Service may be down. HTTP Status: $response"
            # Try pinging a few more times
            for i in {1..3}; do
              echo "Retry attempt $i..."
              sleep 10
              response=$(curl -s -o /dev/null -w "%{http_code}" "$RENDER_URL/" || echo "000")
              if [ "$response" = "200" ] || [ "$response" = "403" ]; then
                echo "✅ Service responded on retry $i! HTTP Status: $response"
                break
              fi
            done
          fi
          
          # Also ping the docs endpoint to ensure the app is fully loaded
          docs_response=$(curl -s -o /dev/null -w "%{http_code}" "$RENDER_URL/docs" || echo "000")
          echo "📚 Docs endpoint status: $docs_response"
          
          # Test authenticated IP endpoint to verify API functionality
          ip_response=$(curl -s -o /dev/null -w "%{http_code}" "$RENDER_URL/proxy/ip?api_password=$API_PASSWORD" || echo "000")
          echo "🌐 IP endpoint status: $ip_response"
          
          # Log timestamp
          echo "🕐 Ping completed at: $(date -u)"

      - name: Check Service Status
        run: |
          echo "=== Service Status Check ==="
          RENDER_URL="https://mediaflow-proxy-0fzf.onrender.com"
          
          # Check if service responds within reasonable time
          echo "Testing response time..."
          time curl -s -m 30 "$RENDER_URL/" > /dev/null && echo "✅ Service responds quickly" || echo "⚠️ Service response is slow"
          
          echo "=== End Status Check ==="
